// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VehicleRepo.Infrastructure.Database;

#nullable disable

namespace VehicleRepo.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220909030454_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VehicleRepo.Core.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Vehicle");
                });

            modelBuilder.Entity("VehicleRepo.Core.Domain.Entities.Boat", b =>
                {
                    b.HasBaseType("VehicleRepo.Core.Domain.Entities.Vehicle");

                    b.HasDiscriminator().HasValue("Boat");
                });

            modelBuilder.Entity("VehicleRepo.Core.Domain.Entities.Bus", b =>
                {
                    b.HasBaseType("VehicleRepo.Core.Domain.Entities.Vehicle");

                    b.HasDiscriminator().HasValue("Bus");
                });

            modelBuilder.Entity("VehicleRepo.Core.Domain.Entities.Car", b =>
                {
                    b.HasBaseType("VehicleRepo.Core.Domain.Entities.Vehicle");

                    b.Property<bool>("HeadlightsAreOn")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Car");
                });
#pragma warning restore 612, 618
        }
    }
}
